# GLOBAL SITE SETTINGS

cname: swellnet.yourwebvisual.com

# META
title: Swellnet
title_homepage:
company:
description:

# SITE DEFAULTS
site_tagline:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/swell-0917
github_repo_name:
jekyll_version: 3.5.0

# OFFICES
offices:
  - title:
    address:
    phone: (02) 9455 123
    email: hello@new-website.com

# SOCIAL MEDIA
facebook:
linked_in:
google_plus:
instagram:

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Much Media
  url: http://muchmedia.com.au
  logo: /assets/img/ui/logo-much-media.svg
  description: WEBSITE BY MUCH MEDIA