# GLOBAL SITE SETTINGS

cname: swellnet.yourwebvisual.com

# META
title: Swellnet
title_homepage:
company: Swellnet Pty Ltd
description:

# SITE DEFAULTS
site_tagline:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/swell-0917
github_repo_name:
jekyll_version: 3.5.0

# OFFICES
offices:
  - title: Sydney
    address: Level 5, 8 West Street<br> North Sydney, NSW, 2060
    phone: 1800 793 556
    email: privacy@swellnet.com

# SOCIAL MEDIA
facebook: https://facebook.com/swellnet/
instagram: https://instagram.com/swellnet/

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Much Media
  url: http://muchmedia.com.au
  logo: /assets/img/ui/logo-much-media.svg
  description: WEBSITE BY MUCH MEDIA